 
package diseño;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Facturas;
import modelo.FacturasDAO;

public class ventas extends javax.swing.JPanel {
     FacturasDAO fdao = new FacturasDAO();
     DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form ventas
     */
    public ventas() {
       
        initComponents();
        contar();
        sumarproductos();
        sumasvalores();
         try {
             llenarjtable(tablaventas);
         } catch (Exception ex) {
             Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbresumen = new javax.swing.JLabel();
        linea = new javax.swing.JPanel();
        cuadroverde = new javax.swing.JPanel();
        lbventastotales = new javax.swing.JLabel();
        tfventastotales = new javax.swing.JTextField();
        cuadroamarrillo = new javax.swing.JPanel();
        lbventasrealizadas = new javax.swing.JLabel();
        tfventasrealizadas = new javax.swing.JTextField();
        cuadroazul = new javax.swing.JPanel();
        lbproductosvendidos = new javax.swing.JLabel();
        tfproductosvendidos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1100, 750));
        setMinimumSize(new java.awt.Dimension(1100, 750));

        lbresumen.setBackground(new java.awt.Color(0, 0, 0));
        lbresumen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbresumen.setForeground(new java.awt.Color(0, 0, 0));
        lbresumen.setText("Resumen");

        linea.setBackground(new java.awt.Color(255, 205, 93));
        linea.setMaximumSize(new java.awt.Dimension(1100, 35));
        linea.setMinimumSize(new java.awt.Dimension(1100, 35));

        javax.swing.GroupLayout lineaLayout = new javax.swing.GroupLayout(linea);
        linea.setLayout(lineaLayout);
        lineaLayout.setHorizontalGroup(
            lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lineaLayout.setVerticalGroup(
            lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        cuadroverde.setBackground(new java.awt.Color(0, 255, 102));
        cuadroverde.setMaximumSize(new java.awt.Dimension(260, 176));
        cuadroverde.setMinimumSize(new java.awt.Dimension(260, 176));

        lbventastotales.setBackground(new java.awt.Color(0, 0, 0));
        lbventastotales.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbventastotales.setForeground(new java.awt.Color(255, 255, 255));
        lbventastotales.setText("Ventas Realizadas");

        tfventastotales.setEditable(false);
        tfventastotales.setBackground(new java.awt.Color(0, 255, 102));
        tfventastotales.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfventastotales.setForeground(new java.awt.Color(255, 255, 255));
        tfventastotales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfventastotales.setBorder(null);
        tfventastotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfventastotalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuadroverdeLayout = new javax.swing.GroupLayout(cuadroverde);
        cuadroverde.setLayout(cuadroverdeLayout);
        cuadroverdeLayout.setHorizontalGroup(
            cuadroverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroverdeLayout.createSequentialGroup()
                .addGroup(cuadroverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuadroverdeLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbventastotales))
                    .addGroup(cuadroverdeLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(tfventastotales, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        cuadroverdeLayout.setVerticalGroup(
            cuadroverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroverdeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbventastotales)
                .addGap(18, 18, 18)
                .addComponent(tfventastotales, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        cuadroamarrillo.setBackground(new java.awt.Color(255, 205, 93));
        cuadroamarrillo.setMaximumSize(new java.awt.Dimension(260, 176));
        cuadroamarrillo.setMinimumSize(new java.awt.Dimension(260, 176));
        cuadroamarrillo.setPreferredSize(new java.awt.Dimension(260, 176));

        lbventasrealizadas.setBackground(new java.awt.Color(0, 0, 0));
        lbventasrealizadas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbventasrealizadas.setForeground(new java.awt.Color(255, 255, 255));
        lbventasrealizadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbventasrealizadas.setText("Ventas Totales");

        tfventasrealizadas.setEditable(false);
        tfventasrealizadas.setBackground(new java.awt.Color(255, 205, 93));
        tfventasrealizadas.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfventasrealizadas.setForeground(new java.awt.Color(255, 255, 255));
        tfventasrealizadas.setBorder(null);
        tfventasrealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfventasrealizadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuadroamarrilloLayout = new javax.swing.GroupLayout(cuadroamarrillo);
        cuadroamarrillo.setLayout(cuadroamarrilloLayout);
        cuadroamarrilloLayout.setHorizontalGroup(
            cuadroamarrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuadroamarrilloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbventasrealizadas)
                .addGap(41, 41, 41))
            .addGroup(cuadroamarrilloLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tfventasrealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        cuadroamarrilloLayout.setVerticalGroup(
            cuadroamarrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroamarrilloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbventasrealizadas)
                .addGap(18, 18, 18)
                .addComponent(tfventasrealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuadroazul.setBackground(new java.awt.Color(18, 177, 158));
        cuadroazul.setMaximumSize(new java.awt.Dimension(260, 176));
        cuadroazul.setMinimumSize(new java.awt.Dimension(260, 176));
        cuadroazul.setPreferredSize(new java.awt.Dimension(260, 176));

        lbproductosvendidos.setBackground(new java.awt.Color(0, 0, 0));
        lbproductosvendidos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbproductosvendidos.setForeground(new java.awt.Color(255, 255, 255));
        lbproductosvendidos.setText("Productos Vendidos");

        tfproductosvendidos.setEditable(false);
        tfproductosvendidos.setBackground(new java.awt.Color(18, 177, 158));
        tfproductosvendidos.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfproductosvendidos.setForeground(new java.awt.Color(255, 255, 255));
        tfproductosvendidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfproductosvendidos.setBorder(null);
        tfproductosvendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfproductosvendidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuadroazulLayout = new javax.swing.GroupLayout(cuadroazul);
        cuadroazul.setLayout(cuadroazulLayout);
        cuadroazulLayout.setHorizontalGroup(
            cuadroazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuadroazulLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lbproductosvendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuadroazulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfproductosvendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cuadroazulLayout.setVerticalGroup(
            cuadroazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroazulLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbproductosvendidos)
                .addGap(18, 18, 18)
                .addComponent(tfproductosvendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tablaventas.setForeground(new java.awt.Color(0, 0, 0));
        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° venta", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaventas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbresumen)
                .addGap(18, 18, 18)
                .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, 950, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cuadroverde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(cuadroamarrillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(cuadroazul, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbresumen))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuadroverde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadroamarrillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadroazul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfventastotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfventastotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfventastotalesActionPerformed

    private void tfproductosvendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfproductosvendidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfproductosvendidosActionPerformed

    private void tfventasrealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfventasrealizadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfventasrealizadasActionPerformed
    public void contar(){
String cuenta;
        tfventastotales.setText( cuenta = String.valueOf(fdao.contarVentas()));
        System.out.println("fdao.contarVentas() = " + fdao.contarVentas());
    }
    public void sumasvalores(){
        String venta;
        tfventasrealizadas.setText("$ ".concat(venta = String.valueOf(fdao.sumarventas())));
    }
    public void sumarproductos(){
    String sumaproductos;
    tfproductosvendidos.setText(sumaproductos = String.valueOf(fdao.sumarproductos()));
    }
    public void llenarjtable(JTable fact) throws Exception {
        try{
        ArrayList<Object> nombre = new ArrayList<>();
        nombre.removeAll(nombre);
        nombre.add("N° Venta");
        nombre.add("Fecha");
        nombre.add("Monto");

        for (Object columna : nombre) {
            modelo.addColumn(columna);
        }

        for (Facturas valores : fdao.listar()) {
            modelo.addRow(new Object[]{valores.getId(), valores.getFecha(), valores.getMonto()});
        }
        fact.setModel(modelo);
        }catch(Exception e){
            System.out.println("Ocurrio un error"+ e.getMessage());
        }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cuadroamarrillo;
    private javax.swing.JPanel cuadroazul;
    private javax.swing.JPanel cuadroverde;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbproductosvendidos;
    private javax.swing.JLabel lbresumen;
    private javax.swing.JLabel lbventasrealizadas;
    private javax.swing.JLabel lbventastotales;
    private javax.swing.JPanel linea;
    private javax.swing.JTable tablaventas;
    private javax.swing.JTextField tfproductosvendidos;
    private javax.swing.JTextField tfventasrealizadas;
    private javax.swing.JTextField tfventastotales;
    // End of variables declaration//GEN-END:variables
}
